version: "3.8"

services:
  fastapi:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - .:/app
    environment:
      - MONGO_URL=mongodb+srv://root:2kIqDOPsy90Cp7pv@cluster0.qwkzh90.mongodb.net/

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
